apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: or.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: or-server
            port:
              number: 3000
  - host: srd.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: srd-server
            port:
              number: 8000
  - host: opv.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opv-server
            port:
              number: 8007
  - host: q.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: q-server
            port:
              number: 8000
  - host: roam.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: roam-server
            port:
              number: 80
